# Generated by Django 3.2.15 on 2023-03-14 12:09

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCircular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Remote', 'Remote'), ('Paid Internship', 'Paid Internship')], max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('vacancy', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/job_circulars/')),
                ('description', django_quill.fields.QuillField()),
                ('experience', models.CharField(max_length=100)),
                ('age_range', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Only males are allowed to apply', 'Only males are allowed to apply'), ('Only females are allowed to apply', 'Only females are allowed to apply'), (' Both males and females are allowed to apply', ' Both males and females are allowed to apply')], max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('working_hour', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
