# Generated by Django 3.2.15 on 2023-03-14 12:54

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='files/cv/', validators=[jobs.models.validate_file_extension], verbose_name='Candidate CV')),
                ('cover_letter', models.FileField(upload_to='files/cover_letter/', validators=[jobs.models.validate_file_extension], verbose_name='Candidate Cover Letter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcircular')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Interviewed', 'Interviewed'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
            ],
        ),
    ]
